# Generated by Django 3.2.2 on 2023-03-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='Availabilty',
            field=models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock')], max_length=100, null=True),
        ),
    ]
